# Generated by Django 3.2.8 on 2021-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="stream",
            new_name="year",
        ),
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CSE", "CSE"),
                    ("ECE", "ECE"),
                    ("EE", "EE"),
                    ("IT", "IT"),
                    ("AEIE", "AEIE"),
                ],
                default="CSE",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="fname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="lname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roll_number",
            field=models.CharField(default="", max_length=11),
        ),
    ]
