# Generated by Django 3.2.8 on 2022-01-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_profile_roll_number'),
        ('Account', '0003_alter_profile_roll_number 2'),
    ]

    operations = [
    ]
