# Generated by Django 3.2.10 on 2022-01-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='edited_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='edited_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
